name: Autograding Tests
'on':
- push
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Directories
      id: directories
      uses: education/autograding-command-grader@v1
      with:
        test-name: Directories
        setup-command: "./tests/setup"
        command: "./tests/test-directories"
        timeout: 10
        max-score: 30
    - name: Remove directory
      id: remove-directory
      uses: education/autograding-command-grader@v1
      with:
        test-name: Remove directory
        setup-command: "./tests/setup"
        command: "./tests/test-remove-directory"
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: education/autograding-grading-reporter@v1
      env:
        DIRECTORIES_RESULTS: "${{steps.directories.outputs.result}}"
        REMOVE-DIRECTORY_RESULTS: "${{steps.remove-directory.outputs.result}}"
      with:
        runners: directories,remove-directory
